### ISSUE TITLE
关于客户端收到服务器推送消息乱码

### ISSUE THREAD

**Issue by toby20130333** [yunba/yunba-c-sdk#1]
发是网页版本进入个人管理发布消息，发布频道topic的System， 收是c sdk，
但是只要网页版本消息内容存在空格的情况，客户端收到的消息空格部分是乱码

开发环境：Mac osx10.10
IDE：qtcreator
框架：Qt
编译器：clang
客户端输出：
"收到系统消息 " 我吾问无为谓哇哇哇哇�K�������K�
服务器发布："我吾问无为谓哇哇哇哇                  "

**Comment by alexbank** [comment]
经测试是OK。请检查下代码

**Comment by toby20130333** [comment]
想问下 你们对windows的兼容 如何处理，看到你们初始化socket的工作都没有做，导致在windows上面没有办法使用
